#type.sql#
SELECT MAX(C.DTNEG)
FROM TGFCAB C
INNER JOIN TGFPAR P ON P.CODPARC = C.CODPARC
WHERE C.CODPARC = TGFPAR.CODPARC


SELECT MAX(C.DTNEG)
FROM TGFCAB C
INNER JOIN TGFPAR P ON P.CODPARC = C.CODPARC
WHERE P.CODPARC = TGFPAR.CODPARC